#!/usr/bin/env python3
"""Generate the packaged native-engine notice asset from reviewed sources."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "apps" / "zagros_vpn" / "assets" / "legal" / "native_engine_notices.txt"


def inputs() -> list[tuple[str, Path]]:
    result = [
        ("REVIEW AND DISTRIBUTION STATUS", ROOT / "THIRD_PARTY_NOTICES.md"),
        (
            "WIREGUARD ANDROID JAVA/KOTLIN — APACHE LICENSE 2.0",
            ROOT / "third_party" / "wireguard-android" / "LICENSE-APACHE-2.0",
        ),
        ("WIREGUARD-GO — MIT LICENSE", ROOT / "third_party" / "wireguard-go" / "LICENSE-MIT"),
        ("SING-BOX DAEMON — GNU GPL 3.0", ROOT / "third_party" / "singbox" / "LICENSE-GPL-3.0"),
        ("HEV-SOCKS5-TUNNEL BRIDGE — MIT LICENSE", ROOT / "third_party" / "hev-socks5-tunnel" / "LICENSE-MIT"),
        ("OPEN SSTP CLIENT ENGINE — MIT LICENSE", ROOT / "third_party" / "sstp-client" / "LICENSE"),
    ]
    module_lock = json.loads(
        (ROOT / "third_party" / "wireguard-go" / "source-license-lock.json").read_text()
    )
    for module in module_lock["modules"]:
        for item in module["license_notice_files"]:
            member = item["module_member"].rsplit("/", 1)[-1]
            result.append(
                (f"GO MODULE {module['module']} {module['version']} — {member}", ROOT / item["path"])
            )
    toolchain_lock = json.loads(
        (ROOT / "third_party" / "wireguard-go" / "go-toolchain-licenses" / "lock.json").read_text()
    )
    for item in toolchain_lock["license_notice_files"]:
        result.append(
            (f"GO {toolchain_lock['go_version']} TOOLCHAIN — {item['archive_member']}", ROOT / item["path"])
        )
    runtime_lock = json.loads(
        (ROOT / "third_party" / "android-runtime" / "lock.json").read_text()
    )
    for item in runtime_lock["licenses"]:
        result.append(
            (f"ANDROID RUNTIME — {Path(item['path']).name}", ROOT / item["path"])
        )
    return result


def render() -> str:
    sections = [
        "ZAGROS NATIVE ENGINE THIRD-PARTY NOTICES\n"
        "Generated by tool/generate_native_notices.py. Do not edit this asset directly.\n"
        "This native-engine notice set is not yet the complete shipping dependency inventory."
    ]
    for title, path in inputs():
        sections.append(f"{title}\n\n{path.read_text(encoding='utf-8').rstrip()}")
    return ("\n\n" + "=" * 78 + "\n\n").join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("packaged native-engine notice asset is missing or stale")
        print("Packaged native-engine notice asset is current.")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
