// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_TUNNEL_API_G_H_
#define PIGEON_TUNNEL_API_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * zagros_tunnelNativeTunnelState:
 * TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_DISCONNECTED:
 * TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_PREPARING:
 * TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_CONNECTING:
 * TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_CONNECTED:
 * TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_DISCONNECTING:
 * TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_FAILED:
 *
 */
typedef enum {
  TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_DISCONNECTED = 0,
  TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_PREPARING = 1,
  TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_CONNECTING = 2,
  TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_CONNECTED = 3,
  TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_DISCONNECTING = 4,
  TUNNEL_INTERFACE_NATIVE_TUNNEL_STATE_FAILED = 5
} zagros_tunnelNativeTunnelState;

/**
 * zagros_tunnelNativeTunnelRequest:
 *
 */

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelRequest, zagros_tunnel_native_tunnel_request, ZAGROS_TUNNEL, NATIVE_TUNNEL_REQUEST, GObject)

/**
 * zagros_tunnel_native_tunnel_request_new:
 * request_id: field in this object.
 * connection_id: field in this object.
 * protocol: field in this object.
 * engine: field in this object.
 * config_payload: field in this object.
 * config_payload_length: length of @config_payload.
 * white_label: field in this object.
 *
 * Creates a new #NativeTunnelRequest object.
 *
 * Returns: a new #zagros_tunnelNativeTunnelRequest
 */
zagros_tunnelNativeTunnelRequest* zagros_tunnel_native_tunnel_request_new(const gchar* request_id, const gchar* connection_id, const gchar* protocol, const gchar* engine, const uint8_t* config_payload, size_t config_payload_length, gboolean white_label);

/**
 * zagros_tunnel_native_tunnel_request_get_request_id
 * @object: a #zagros_tunnelNativeTunnelRequest.
 *
 * Gets the value of the requestId field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_request_get_request_id(zagros_tunnelNativeTunnelRequest* object);

/**
 * zagros_tunnel_native_tunnel_request_get_connection_id
 * @object: a #zagros_tunnelNativeTunnelRequest.
 *
 * Gets the value of the connectionId field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_request_get_connection_id(zagros_tunnelNativeTunnelRequest* object);

/**
 * zagros_tunnel_native_tunnel_request_get_protocol
 * @object: a #zagros_tunnelNativeTunnelRequest.
 *
 * Gets the value of the protocol field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_request_get_protocol(zagros_tunnelNativeTunnelRequest* object);

/**
 * zagros_tunnel_native_tunnel_request_get_engine
 * @object: a #zagros_tunnelNativeTunnelRequest.
 *
 * Gets the value of the engine field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_request_get_engine(zagros_tunnelNativeTunnelRequest* object);

/**
 * zagros_tunnel_native_tunnel_request_get_config_payload
 * @object: a #zagros_tunnelNativeTunnelRequest.
 * @length: location to write the length of this value.
 *
 * Gets the value of the configPayload field of @object.
 *
 * Returns: the field value.
 */
const uint8_t* zagros_tunnel_native_tunnel_request_get_config_payload(zagros_tunnelNativeTunnelRequest* object, size_t* length);

/**
 * zagros_tunnel_native_tunnel_request_get_white_label
 * @object: a #zagros_tunnelNativeTunnelRequest.
 *
 * Gets the value of the whiteLabel field of @object.
 *
 * Returns: the field value.
 */
gboolean zagros_tunnel_native_tunnel_request_get_white_label(zagros_tunnelNativeTunnelRequest* object);

/**
 * zagros_tunnel_native_tunnel_request_equals:
 * @a: a #zagros_tunnelNativeTunnelRequest.
 * @b: another #zagros_tunnelNativeTunnelRequest.
 *
 * Checks if two #zagros_tunnelNativeTunnelRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean zagros_tunnel_native_tunnel_request_equals(zagros_tunnelNativeTunnelRequest* a, zagros_tunnelNativeTunnelRequest* b);

/**
 * zagros_tunnel_native_tunnel_request_hash:
 * @object: a #zagros_tunnelNativeTunnelRequest.
 *
 * Calculates a hash code for a #zagros_tunnelNativeTunnelRequest object.
 *
 * Returns: the hash code.
 */
guint zagros_tunnel_native_tunnel_request_hash(zagros_tunnelNativeTunnelRequest* object);

/**
 * zagros_tunnel_native_tunnel_request_to_string:
 * @object: a #zagros_tunnelNativeTunnelRequest.
 *
 * Returns a string representation of a #zagros_tunnelNativeTunnelRequest object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* zagros_tunnel_native_tunnel_request_to_string(zagros_tunnelNativeTunnelRequest* object);

/**
 * zagros_tunnelNativeTunnelStatus:
 *
 */

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelStatus, zagros_tunnel_native_tunnel_status, ZAGROS_TUNNEL, NATIVE_TUNNEL_STATUS, GObject)

/**
 * zagros_tunnel_native_tunnel_status_new:
 * state: field in this object.
 * sequence: field in this object.
 * uplink_bytes: field in this object.
 * downlink_bytes: field in this object.
 * connection_id: field in this object.
 * protocol: field in this object.
 * connected_at_epoch_ms: field in this object.
 * failure_code: field in this object.
 * safe_failure_message: field in this object.
 *
 * Creates a new #NativeTunnelStatus object.
 *
 * Returns: a new #zagros_tunnelNativeTunnelStatus
 */
zagros_tunnelNativeTunnelStatus* zagros_tunnel_native_tunnel_status_new(zagros_tunnelNativeTunnelState state, int64_t sequence, int64_t uplink_bytes, int64_t downlink_bytes, const gchar* connection_id, const gchar* protocol, int64_t* connected_at_epoch_ms, const gchar* failure_code, const gchar* safe_failure_message);

/**
 * zagros_tunnel_native_tunnel_status_get_state
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the state field of @object.
 *
 * Returns: the field value.
 */
zagros_tunnelNativeTunnelState zagros_tunnel_native_tunnel_status_get_state(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_get_sequence
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the sequence field of @object.
 *
 * Returns: the field value.
 */
int64_t zagros_tunnel_native_tunnel_status_get_sequence(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_get_uplink_bytes
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the uplinkBytes field of @object.
 *
 * Returns: the field value.
 */
int64_t zagros_tunnel_native_tunnel_status_get_uplink_bytes(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_get_downlink_bytes
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the downlinkBytes field of @object.
 *
 * Returns: the field value.
 */
int64_t zagros_tunnel_native_tunnel_status_get_downlink_bytes(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_get_connection_id
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the connectionId field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_status_get_connection_id(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_get_protocol
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the protocol field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_status_get_protocol(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_get_connected_at_epoch_ms
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the connectedAtEpochMs field of @object.
 *
 * Returns: the field value.
 */
int64_t* zagros_tunnel_native_tunnel_status_get_connected_at_epoch_ms(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_get_failure_code
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the failureCode field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_status_get_failure_code(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_get_safe_failure_message
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Gets the value of the safeFailureMessage field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_status_get_safe_failure_message(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_equals:
 * @a: a #zagros_tunnelNativeTunnelStatus.
 * @b: another #zagros_tunnelNativeTunnelStatus.
 *
 * Checks if two #zagros_tunnelNativeTunnelStatus objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean zagros_tunnel_native_tunnel_status_equals(zagros_tunnelNativeTunnelStatus* a, zagros_tunnelNativeTunnelStatus* b);

/**
 * zagros_tunnel_native_tunnel_status_hash:
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Calculates a hash code for a #zagros_tunnelNativeTunnelStatus object.
 *
 * Returns: the hash code.
 */
guint zagros_tunnel_native_tunnel_status_hash(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnel_native_tunnel_status_to_string:
 * @object: a #zagros_tunnelNativeTunnelStatus.
 *
 * Returns a string representation of a #zagros_tunnelNativeTunnelStatus object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* zagros_tunnel_native_tunnel_status_to_string(zagros_tunnelNativeTunnelStatus* object);

/**
 * zagros_tunnelNativeTunnelCapabilities:
 *
 */

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelCapabilities, zagros_tunnel_native_tunnel_capabilities, ZAGROS_TUNNEL, NATIVE_TUNNEL_CAPABILITIES, GObject)

/**
 * zagros_tunnel_native_tunnel_capabilities_new:
 * platform: field in this object.
 * protocols: field in this object.
 * can_protect_entire_device: field in this object.
 * can_report_traffic: field in this object.
 * unavailable_reasons: field in this object.
 *
 * Creates a new #NativeTunnelCapabilities object.
 *
 * Returns: a new #zagros_tunnelNativeTunnelCapabilities
 */
zagros_tunnelNativeTunnelCapabilities* zagros_tunnel_native_tunnel_capabilities_new(const gchar* platform, FlValue* protocols, gboolean can_protect_entire_device, gboolean can_report_traffic, FlValue* unavailable_reasons);

/**
 * zagros_tunnel_native_tunnel_capabilities_get_platform
 * @object: a #zagros_tunnelNativeTunnelCapabilities.
 *
 * Gets the value of the platform field of @object.
 *
 * Returns: the field value.
 */
const gchar* zagros_tunnel_native_tunnel_capabilities_get_platform(zagros_tunnelNativeTunnelCapabilities* object);

/**
 * zagros_tunnel_native_tunnel_capabilities_get_protocols
 * @object: a #zagros_tunnelNativeTunnelCapabilities.
 *
 * Gets the value of the protocols field of @object.
 *
 * Returns: the field value.
 */
FlValue* zagros_tunnel_native_tunnel_capabilities_get_protocols(zagros_tunnelNativeTunnelCapabilities* object);

/**
 * zagros_tunnel_native_tunnel_capabilities_get_can_protect_entire_device
 * @object: a #zagros_tunnelNativeTunnelCapabilities.
 *
 * Gets the value of the canProtectEntireDevice field of @object.
 *
 * Returns: the field value.
 */
gboolean zagros_tunnel_native_tunnel_capabilities_get_can_protect_entire_device(zagros_tunnelNativeTunnelCapabilities* object);

/**
 * zagros_tunnel_native_tunnel_capabilities_get_can_report_traffic
 * @object: a #zagros_tunnelNativeTunnelCapabilities.
 *
 * Gets the value of the canReportTraffic field of @object.
 *
 * Returns: the field value.
 */
gboolean zagros_tunnel_native_tunnel_capabilities_get_can_report_traffic(zagros_tunnelNativeTunnelCapabilities* object);

/**
 * zagros_tunnel_native_tunnel_capabilities_get_unavailable_reasons
 * @object: a #zagros_tunnelNativeTunnelCapabilities.
 *
 * Gets the value of the unavailableReasons field of @object.
 *
 * Returns: the field value.
 */
FlValue* zagros_tunnel_native_tunnel_capabilities_get_unavailable_reasons(zagros_tunnelNativeTunnelCapabilities* object);

/**
 * zagros_tunnel_native_tunnel_capabilities_equals:
 * @a: a #zagros_tunnelNativeTunnelCapabilities.
 * @b: another #zagros_tunnelNativeTunnelCapabilities.
 *
 * Checks if two #zagros_tunnelNativeTunnelCapabilities objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean zagros_tunnel_native_tunnel_capabilities_equals(zagros_tunnelNativeTunnelCapabilities* a, zagros_tunnelNativeTunnelCapabilities* b);

/**
 * zagros_tunnel_native_tunnel_capabilities_hash:
 * @object: a #zagros_tunnelNativeTunnelCapabilities.
 *
 * Calculates a hash code for a #zagros_tunnelNativeTunnelCapabilities object.
 *
 * Returns: the hash code.
 */
guint zagros_tunnel_native_tunnel_capabilities_hash(zagros_tunnelNativeTunnelCapabilities* object);

/**
 * zagros_tunnel_native_tunnel_capabilities_to_string:
 * @object: a #zagros_tunnelNativeTunnelCapabilities.
 *
 * Returns a string representation of a #zagros_tunnelNativeTunnelCapabilities object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* zagros_tunnel_native_tunnel_capabilities_to_string(zagros_tunnelNativeTunnelCapabilities* object);

G_DECLARE_FINAL_TYPE(zagros_tunnelMessageCodec, zagros_tunnel_message_codec, ZAGROS_TUNNEL, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int zagros_tunnel_native_tunnel_state_type_id;
extern const int zagros_tunnel_native_tunnel_request_type_id;
extern const int zagros_tunnel_native_tunnel_status_type_id;
extern const int zagros_tunnel_native_tunnel_capabilities_type_id;

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelHostApi, zagros_tunnel_native_tunnel_host_api, ZAGROS_TUNNEL, NATIVE_TUNNEL_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelHostApiResponseHandle, zagros_tunnel_native_tunnel_host_api_response_handle, ZAGROS_TUNNEL, NATIVE_TUNNEL_HOST_API_RESPONSE_HANDLE, GObject)

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelHostApiGetCapabilitiesResponse, zagros_tunnel_native_tunnel_host_api_get_capabilities_response, ZAGROS_TUNNEL, NATIVE_TUNNEL_HOST_API_GET_CAPABILITIES_RESPONSE, GObject)

/**
 * zagros_tunnel_native_tunnel_host_api_get_capabilities_response_new:
 *
 * Creates a new response to NativeTunnelHostApi.getCapabilities.
 *
 * Returns: a new #zagros_tunnelNativeTunnelHostApiGetCapabilitiesResponse
 */
zagros_tunnelNativeTunnelHostApiGetCapabilitiesResponse* zagros_tunnel_native_tunnel_host_api_get_capabilities_response_new(zagros_tunnelNativeTunnelCapabilities* return_value);

/**
 * zagros_tunnel_native_tunnel_host_api_get_capabilities_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeTunnelHostApi.getCapabilities.
 *
 * Returns: a new #zagros_tunnelNativeTunnelHostApiGetCapabilitiesResponse
 */
zagros_tunnelNativeTunnelHostApiGetCapabilitiesResponse* zagros_tunnel_native_tunnel_host_api_get_capabilities_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelHostApiGetStatusResponse, zagros_tunnel_native_tunnel_host_api_get_status_response, ZAGROS_TUNNEL, NATIVE_TUNNEL_HOST_API_GET_STATUS_RESPONSE, GObject)

/**
 * zagros_tunnel_native_tunnel_host_api_get_status_response_new:
 *
 * Creates a new response to NativeTunnelHostApi.getStatus.
 *
 * Returns: a new #zagros_tunnelNativeTunnelHostApiGetStatusResponse
 */
zagros_tunnelNativeTunnelHostApiGetStatusResponse* zagros_tunnel_native_tunnel_host_api_get_status_response_new(zagros_tunnelNativeTunnelStatus* return_value);

/**
 * zagros_tunnel_native_tunnel_host_api_get_status_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeTunnelHostApi.getStatus.
 *
 * Returns: a new #zagros_tunnelNativeTunnelHostApiGetStatusResponse
 */
zagros_tunnelNativeTunnelHostApiGetStatusResponse* zagros_tunnel_native_tunnel_host_api_get_status_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * zagros_tunnelNativeTunnelHostApiVTable:
 *
 * Table of functions exposed by NativeTunnelHostApi to be implemented by the API provider.
 */
typedef struct {
  zagros_tunnelNativeTunnelHostApiGetCapabilitiesResponse* (*get_capabilities)(gpointer user_data);
  zagros_tunnelNativeTunnelHostApiGetStatusResponse* (*get_status)(gpointer user_data);
  void (*connect)(zagros_tunnelNativeTunnelRequest* request, zagros_tunnelNativeTunnelHostApiResponseHandle* response_handle, gpointer user_data);
  void (*disconnect)(const gchar* reason, zagros_tunnelNativeTunnelHostApiResponseHandle* response_handle, gpointer user_data);
} zagros_tunnelNativeTunnelHostApiVTable;

/**
 * zagros_tunnel_native_tunnel_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the NativeTunnelHostApi API.
 */
void zagros_tunnel_native_tunnel_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const zagros_tunnelNativeTunnelHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * zagros_tunnel_native_tunnel_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the NativeTunnelHostApi API.
 */
void zagros_tunnel_native_tunnel_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * zagros_tunnel_native_tunnel_host_api_respond_connect:
 * @response_handle: a #zagros_tunnelNativeTunnelHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to NativeTunnelHostApi.connect. 
 */
void zagros_tunnel_native_tunnel_host_api_respond_connect(zagros_tunnelNativeTunnelHostApiResponseHandle* response_handle, zagros_tunnelNativeTunnelStatus* return_value);

/**
 * zagros_tunnel_native_tunnel_host_api_respond_error_connect:
 * @response_handle: a #zagros_tunnelNativeTunnelHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to NativeTunnelHostApi.connect. 
 */
void zagros_tunnel_native_tunnel_host_api_respond_error_connect(zagros_tunnelNativeTunnelHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * zagros_tunnel_native_tunnel_host_api_respond_disconnect:
 * @response_handle: a #zagros_tunnelNativeTunnelHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to NativeTunnelHostApi.disconnect. 
 */
void zagros_tunnel_native_tunnel_host_api_respond_disconnect(zagros_tunnelNativeTunnelHostApiResponseHandle* response_handle, zagros_tunnelNativeTunnelStatus* return_value);

/**
 * zagros_tunnel_native_tunnel_host_api_respond_error_disconnect:
 * @response_handle: a #zagros_tunnelNativeTunnelHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to NativeTunnelHostApi.disconnect. 
 */
void zagros_tunnel_native_tunnel_host_api_respond_error_disconnect(zagros_tunnelNativeTunnelHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse, zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response, ZAGROS_TUNNEL, NATIVE_TUNNEL_FLUTTER_API_ON_STATUS_CHANGED_RESPONSE, GObject)

/**
 * zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response_is_error:
 * @response: a #zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse.
 *
 * Checks if a response to NativeTunnelFlutterApi.onStatusChanged is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response_is_error(zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse* response);

/**
 * zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response_get_error_code:
 * @response: a #zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response_get_error_code(zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse* response);

/**
 * zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response_get_error_message:
 * @response: a #zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response_get_error_message(zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse* response);

/**
 * zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response_get_error_details:
 * @response: a #zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* zagros_tunnel_native_tunnel_flutter_api_on_status_changed_response_get_error_details(zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse* response);

/**
 * zagros_tunnelNativeTunnelFlutterApi:
 *
 */

G_DECLARE_FINAL_TYPE(zagros_tunnelNativeTunnelFlutterApi, zagros_tunnel_native_tunnel_flutter_api, ZAGROS_TUNNEL, NATIVE_TUNNEL_FLUTTER_API, GObject)

/**
 * zagros_tunnel_native_tunnel_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the NativeTunnelFlutterApi API.
 *
 * Returns: a new #zagros_tunnelNativeTunnelFlutterApi
 */
zagros_tunnelNativeTunnelFlutterApi* zagros_tunnel_native_tunnel_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * zagros_tunnel_native_tunnel_flutter_api_on_status_changed:
 * @api: a #zagros_tunnelNativeTunnelFlutterApi.
 * @status: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void zagros_tunnel_native_tunnel_flutter_api_on_status_changed(zagros_tunnelNativeTunnelFlutterApi* api, zagros_tunnelNativeTunnelStatus* status, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * zagros_tunnel_native_tunnel_flutter_api_on_status_changed_finish:
 * @api: a #zagros_tunnelNativeTunnelFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a zagros_tunnel_native_tunnel_flutter_api_on_status_changed() call.
 *
 * Returns: a #zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse or %NULL on error.
 */
zagros_tunnelNativeTunnelFlutterApiOnStatusChangedResponse* zagros_tunnel_native_tunnel_flutter_api_on_status_changed_finish(zagros_tunnelNativeTunnelFlutterApi* api, GAsyncResult* result, GError** error);

G_END_DECLS

#endif  // PIGEON_TUNNEL_API_G_H_
