// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_TUNNEL_API_G_H_
#define PIGEON_TUNNEL_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace zagros_tunnel {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class NativeTunnelHostApi;
  friend class NativeTunnelFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class NativeTunnelState {
  kDisconnected = 0,
  kPreparing = 1,
  kConnecting = 2,
  kConnected = 3,
  kDisconnecting = 4,
  kFailed = 5
};


// Generated class from Pigeon that represents data sent in messages.
class NativeTunnelRequest {
 public:
  // Constructs an object setting all fields.
  explicit NativeTunnelRequest(
    const std::string& request_id,
    const std::string& connection_id,
    const std::string& protocol,
    const std::string& engine,
    const std::vector<uint8_t>& config_payload,
    bool white_label);
  ~NativeTunnelRequest();

  const std::string& request_id() const;
  void set_request_id(std::string_view value_arg);

  const std::string& connection_id() const;
  void set_connection_id(std::string_view value_arg);

  const std::string& protocol() const;
  void set_protocol(std::string_view value_arg);

  const std::string& engine() const;
  void set_engine(std::string_view value_arg);

  const std::vector<uint8_t>& config_payload() const;
  void set_config_payload(const std::vector<uint8_t>& value_arg);

  bool white_label() const;
  void set_white_label(bool value_arg);

  bool operator==(const NativeTunnelRequest& other) const;
  bool operator!=(const NativeTunnelRequest& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const NativeTunnelRequest& obj);
 private:
  static NativeTunnelRequest FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class NativeTunnelHostApi;
  friend class NativeTunnelFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string request_id_;
  std::string connection_id_;
  std::string protocol_;
  std::string engine_;
  std::vector<uint8_t> config_payload_;
  bool white_label_;
};


// Generated class from Pigeon that represents data sent in messages.
class NativeTunnelStatus {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit NativeTunnelStatus(
    const NativeTunnelState& state,
    int64_t sequence,
    int64_t uplink_bytes,
    int64_t downlink_bytes);

  // Constructs an object setting all fields.
  explicit NativeTunnelStatus(
    const NativeTunnelState& state,
    int64_t sequence,
    int64_t uplink_bytes,
    int64_t downlink_bytes,
    const std::string* connection_id,
    const std::string* protocol,
    const int64_t* connected_at_epoch_ms,
    const std::string* failure_code,
    const std::string* safe_failure_message);

  const NativeTunnelState& state() const;
  void set_state(const NativeTunnelState& value_arg);

  int64_t sequence() const;
  void set_sequence(int64_t value_arg);

  int64_t uplink_bytes() const;
  void set_uplink_bytes(int64_t value_arg);

  int64_t downlink_bytes() const;
  void set_downlink_bytes(int64_t value_arg);

  const std::string* connection_id() const;
  void set_connection_id(const std::string_view* value_arg);
  void set_connection_id(std::string_view value_arg);

  const std::string* protocol() const;
  void set_protocol(const std::string_view* value_arg);
  void set_protocol(std::string_view value_arg);

  const int64_t* connected_at_epoch_ms() const;
  void set_connected_at_epoch_ms(const int64_t* value_arg);
  void set_connected_at_epoch_ms(int64_t value_arg);

  const std::string* failure_code() const;
  void set_failure_code(const std::string_view* value_arg);
  void set_failure_code(std::string_view value_arg);

  const std::string* safe_failure_message() const;
  void set_safe_failure_message(const std::string_view* value_arg);
  void set_safe_failure_message(std::string_view value_arg);

  bool operator==(const NativeTunnelStatus& other) const;
  bool operator!=(const NativeTunnelStatus& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const NativeTunnelStatus& obj);
 private:
  static NativeTunnelStatus FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class NativeTunnelHostApi;
  friend class NativeTunnelFlutterApi;
  friend class PigeonInternalCodecSerializer;
  NativeTunnelState state_;
  int64_t sequence_;
  int64_t uplink_bytes_;
  int64_t downlink_bytes_;
  std::optional<std::string> connection_id_;
  std::optional<std::string> protocol_;
  std::optional<int64_t> connected_at_epoch_ms_;
  std::optional<std::string> failure_code_;
  std::optional<std::string> safe_failure_message_;
};


// Generated class from Pigeon that represents data sent in messages.
class NativeTunnelCapabilities {
 public:
  // Constructs an object setting all fields.
  explicit NativeTunnelCapabilities(
    const std::string& platform,
    const ::flutter::EncodableList& protocols,
    bool can_protect_entire_device,
    bool can_report_traffic,
    const ::flutter::EncodableMap& unavailable_reasons);

  const std::string& platform() const;
  void set_platform(std::string_view value_arg);

  const ::flutter::EncodableList& protocols() const;
  void set_protocols(const ::flutter::EncodableList& value_arg);

  bool can_protect_entire_device() const;
  void set_can_protect_entire_device(bool value_arg);

  bool can_report_traffic() const;
  void set_can_report_traffic(bool value_arg);

  const ::flutter::EncodableMap& unavailable_reasons() const;
  void set_unavailable_reasons(const ::flutter::EncodableMap& value_arg);

  bool operator==(const NativeTunnelCapabilities& other) const;
  bool operator!=(const NativeTunnelCapabilities& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const NativeTunnelCapabilities& obj);
 private:
  static NativeTunnelCapabilities FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class NativeTunnelHostApi;
  friend class NativeTunnelFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string platform_;
  ::flutter::EncodableList protocols_;
  bool can_protect_entire_device_;
  bool can_report_traffic_;
  ::flutter::EncodableMap unavailable_reasons_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class NativeTunnelHostApi {
 public:
  NativeTunnelHostApi(const NativeTunnelHostApi&) = delete;
  NativeTunnelHostApi& operator=(const NativeTunnelHostApi&) = delete;
  virtual ~NativeTunnelHostApi() {}
  virtual ErrorOr<NativeTunnelCapabilities> GetCapabilities() = 0;
  virtual ErrorOr<NativeTunnelStatus> GetStatus() = 0;
  virtual void Connect(
    const NativeTunnelRequest& request,
    std::function<void(ErrorOr<NativeTunnelStatus> reply)> result) = 0;
  virtual void Disconnect(
    const std::string& reason,
    std::function<void(ErrorOr<NativeTunnelStatus> reply)> result) = 0;

  // The codec used by NativeTunnelHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `NativeTunnelHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    NativeTunnelHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    NativeTunnelHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  NativeTunnelHostApi() = default;
};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class NativeTunnelFlutterApi {
 public:
  NativeTunnelFlutterApi(::flutter::BinaryMessenger* binary_messenger);
  NativeTunnelFlutterApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  void OnStatusChanged(
    const NativeTunnelStatus& status,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace zagros_tunnel
#endif  // PIGEON_TUNNEL_API_G_H_
